services:
  - type: web
    name: fake-news-detector
    runtime: python

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python -c "import nltk; nltk.download('stopwords')"

    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0

    plan: free